// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGrVlB2iQB2OFIdnBS8NJJunUOcTZb1g',
    appId: '1:560196331624:android:f2c2508bfeaad7cf0ff3dd',
    messagingSenderId: '560196331624',
    projectId: 'chatting-app-e4ba9',
    storageBucket: 'chatting-app-e4ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2N4JUan4pYaJG3GGVe8MdP6QBpDagB8',
    appId: '1:560196331624:ios:794043d1cff51b340ff3dd',
    messagingSenderId: '560196331624',
    projectId: 'chatting-app-e4ba9',
    storageBucket: 'chatting-app-e4ba9.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-M_3vJT9sRWLrXIyebZynPGLJk3ZMGcY',
    appId: '1:560196331624:web:06d1e6400483dd240ff3dd',
    messagingSenderId: '560196331624',
    projectId: 'chatting-app-e4ba9',
    authDomain: 'chatting-app-e4ba9.firebaseapp.com',
    storageBucket: 'chatting-app-e4ba9.firebasestorage.app',
    measurementId: 'G-58N3HK5G6B',
  );

}